"""Layer 0 — Connector exception hierarchy.

All Connector-layer errors extend ConnectorError (not PropertyAIException).
They are caught by BaseTool.run() and converted to ToolResult(success=False),
so they never reach the HTTP handler.
"""


class ConnectorError(Exception):
    """Base class for all Connector-layer exceptions."""


class ConnectorHttpError(ConnectorError):
    """Raised when an external API returns a non-2xx status code.

    The error_code is generated by the concrete connector's _map_error() method,
    e.g. "PTV_RATE_LIMITED", "GOOGLE_ROUTES_UNREACHABLE".

    Args:
        status_code: HTTP status code from the failing response.
        error_code: Domain-specific error code from _map_error().
        response_body: Raw response body text for debugging.
    """

    def __init__(self, status_code: int, error_code: str, response_body: str) -> None:
        super().__init__(f"HTTP {status_code}: {error_code}")
        self.status_code: int = status_code
        self.error_code: str = error_code
        self.response_body: str = response_body


class ConnectorTimeoutError(ConnectorError):
    """Raised when retries are exhausted due to repeated timeouts.

    Args:
        path: The API endpoint path that timed out.
        attempts: Total number of attempts made (1 + max_retries).
    """

    def __init__(self, path: str, attempts: int) -> None:
        super().__init__(f"Request to {path} timed out after {attempts} attempts")
        self.path: str = path
        self.attempts: int = attempts


# === Layer 1 (BaseConnector + ConnectorConfig) will be added in Subtask 2 ===
