"""create_chats

Revision ID: 993128e7e195
Revises:
Create Date: 2026-06-24 22:42:55.948841

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "993128e7e195"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("anon_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("schema_version", sa.Text(), nullable=False),
        sa.Column("initial_intent", sa.Text(), nullable=True),
        sa.Column("collected_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_needs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("borrowing_capacity", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "NOT (user_id IS NOT NULL AND anon_id IS NOT NULL)", name="chk_chats_single_owner"
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "idx_chats_anon_id",
        "chats",
        ["anon_id"],
        unique=False,
        postgresql_where="anon_id IS NOT NULL",
    )
    op.create_index("idx_chats_status", "chats", ["status"], unique=False)
    op.create_index("idx_chats_updated_at", "chats", ["updated_at"], unique=False)
    op.create_index(
        "idx_chats_user_id",
        "chats",
        ["user_id"],
        unique=False,
        postgresql_where="user_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_chats_user_id", table_name="chats", postgresql_where="user_id IS NOT NULL")
    op.drop_index("idx_chats_updated_at", table_name="chats")
    op.drop_index("idx_chats_status", table_name="chats")
    op.drop_index("idx_chats_anon_id", table_name="chats", postgresql_where="anon_id IS NOT NULL")
    op.drop_table("chats")
    # ### end Alembic commands ###
