"""Layer 0 — Connector exception hierarchy and Layer 1 — BaseConnector.

All Connector-layer errors extend ConnectorError (not PropertyAIException).
They are caught by BaseTool.run() and converted to ToolResult(success=False),
so they never reach the HTTP handler.
"""

from __future__ import annotations

import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import httpx

# ============================================================================
# Layer 0 — Exception Hierarchy
# ============================================================================


class ConnectorError(Exception):
    """Base class for all Connector-layer exceptions."""


class ConnectorHttpError(ConnectorError):
    """Raised when an external API returns a non-2xx status code.

    The error_code is generated by the concrete connector's _map_error() method,
    e.g. "PTV_RATE_LIMITED", "GOOGLE_ROUTES_UNREACHABLE".

    Args:
        status_code: HTTP status code from the failing response.
        error_code: Domain-specific error code from _map_error().
        response_body: Raw response body text for debugging.
    """

    def __init__(self, status_code: int, error_code: str, response_body: str) -> None:
        super().__init__(f"HTTP {status_code}: {error_code}")
        self.status_code: int = status_code
        self.error_code: str = error_code
        self.response_body: str = response_body


class ConnectorTimeoutError(ConnectorError):
    """Raised when retries are exhausted due to repeated timeouts.

    Args:
        path: The API endpoint path that timed out.
        attempts: Total number of attempts made (1 + max_retries).
    """

    def __init__(self, path: str, attempts: int) -> None:
        super().__init__(f"Request to {path} timed out after {attempts} attempts")
        self.path: str = path
        self.attempts: int = attempts


# ============================================================================
# Layer 1 — BaseConnector + ConnectorConfig
# ============================================================================


@dataclass(frozen=True)
class ConnectorConfig:
    """Immutable configuration for a BaseConnector.

    Args:
        base_url: Base URL for the external API (e.g. "https://api.example.com").
        default_timeout_secs: Per-request timeout in seconds.
        max_retries: Maximum retry attempts on timeout before giving up.
        retry_backoff_base_secs: Base delay in seconds between retries.
    """

    base_url: str
    default_timeout_secs: float = 5.0
    max_retries: int = 2
    retry_backoff_base_secs: float = 1.0


class BaseConnector(ABC):
    """Abstract base for all external-API connectors.

    Provides lazy client initialisation, auth injection, error mapping,
    and a retry loop around httpx.AsyncClient.send().  Concrete connectors
    implement _build_auth_async and _map_error.
    """

    def __init__(self, config: ConnectorConfig) -> None:
        self.config: ConnectorConfig = config
        self._client: httpx.AsyncClient | None = None

    # ── Abstract interface ──────────────────────────────────────────────

    @abstractmethod
    async def _build_auth_async(self, request: httpx.Request) -> httpx.Request:
        """Apply authentication to the request (e.g. add an API key header).

        Called on every request, immediately before client.send().

        Args:
            request: The built httpx.Request, ready for auth injection.

        Returns:
            The same request object with auth headers applied.
        """
        ...

    @abstractmethod
    def _map_error(self, status_code: int, response_body: str) -> str:
        """Map an HTTP error response to a domain-specific error code.

        Args:
            status_code: HTTP status code from the failing response.
            response_body: Raw response body text.

        Returns:
            A domain error code string, e.g. "PTV_RATE_LIMITED".
        """
        ...

    # ── HTTP infrastructure ─────────────────────────────────────────────

    async def _get_client_async(self) -> httpx.AsyncClient:
        """Return a lazily-initialised httpx.AsyncClient.

        The client is created with base_url and timeout from the config.
        Subsequent calls return the same instance.
        """
        if self._client is None:
            self._client = httpx.AsyncClient(
                base_url=self.config.base_url,
                timeout=self.config.default_timeout_secs,
            )
        return self._client

    async def _request_async(
        self,
        method: str,
        path: str,
        params: dict[str, Any] | None = None,
        json_body: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Execute an HTTP request with retry-on-timeout logic.

        Args:
            method: HTTP method ("GET", "POST", etc.).
            path: URL path relative to base_url (e.g. "/v3/stops").
            params: Optional query string parameters.
            json_body: Optional JSON request body.

        Returns:
            Parsed JSON response body as a dict.

        Raises:
            ConnectorHttpError: On any non-2xx response (no retry).
            ConnectorTimeoutError: When all retry attempts are exhausted.
        """
        client: httpx.AsyncClient = await self._get_client_async()
        total_attempts: int = self.config.max_retries + 1

        for attempt in range(total_attempts):
            try:
                # Build → Auth is deliberately two steps, not one.
                # _build_auth_async receives the full request (URL + params + body)
                # so that connectors can modify whatever they need:
                #   - PTVConnector:  computes HMAC-SHA1 over path + sorted query
                #     and appends devid + signature to request.url params.
                #   - GoogleRoutes:  adds X-Goog-Api-Key to request.headers.
                #   - DomainConnector: adds Authorization: Bearer to request.headers.
                # A single request → request hook keeps all auth logic in one place,
                # regardless of whether auth touches the URL or the headers.
                raw_request: httpx.Request = client.build_request(
                    method=method,
                    url=path,
                    params=params,
                    json=json_body,
                )
                authed_request: httpx.Request = await self._build_auth_async(raw_request)
                response: httpx.Response = await client.send(authed_request)
                response.raise_for_status()
                result: dict[str, Any] = response.json()
                return result
            except httpx.HTTPStatusError as e:
                error_code: str = self._map_error(
                    e.response.status_code,
                    e.response.text,
                )
                raise ConnectorHttpError(
                    status_code=e.response.status_code,
                    error_code=error_code,
                    response_body=e.response.text,
                ) from e
            except httpx.TimeoutException:
                is_last: bool = attempt == total_attempts - 1
                if is_last:
                    raise ConnectorTimeoutError(
                        path=path,
                        attempts=total_attempts,
                    )
                await asyncio.sleep(self.config.retry_backoff_base_secs)

        # Unreachable — the final iteration either returns or raises above.
        raise ConnectorTimeoutError(path=path, attempts=total_attempts)  # pragma: no cover

    async def close_async(self) -> None:
        """Close the underlying httpx client, if it was initialised."""
        if self._client is not None:
            await self._client.aclose()
            self._client = None
